GET https://www.localizacar.info/api/coches/{matricula}
###

GET https://www.localizacar.info/api/coches/ABC-1234
###

POST https://www.localizacar.info/api/coches
Content-Type: application/json

{
    "matricula": "XYZ-9876",
    "marca": "Toyota",
    "color": "Rojo"
}

###

PUT https://www.localizacar.info/api/coches/{matricula}
Content-Type: application/json

{
    "marca": "Toyota",
    "color": "Negro"
}
###

PUT https://www.localizacar.info/api/coches/XYZ-9876
Content-Type: application/json

{
    "marca": "Toyota",
    "color": "Negro"
}
###

DELETE https://www.localizacar.info/api/coches/{matricula}
###

DELETE https://www.localizacar.info/api/coches/XYZ-9876
