##
GET http://localhost:3000/api/grupos

###
POST http://localhost:3000/api/grupos
Content-Type: application/json

{
    "nombre": "Grupo A",
    "descripcion": "Descripción del Grupo A"
}
###
GET http://localhost:3000/api/grupos/9
###

DELETE http://localhost:3000/api/grupos/1

###

GET http://localhost:3000/api/grupos/1/mensajes
###

POST http://localhost:3000/api/grupos/1/mensajes
Content-Type: application/json

{
    "usermail": "john.doe@example.com",
    "contenido": "Este es un mensaje"
}
###

DELETE http://localhost:3000/api/grupos/mensajes/4

###

POST http://localhost:3000/api/grupos/9/usuarios
Content-Type: application/json

{
    "usermail": "a"
}

###

DELETE http://localhost:3000/api/grupos/9/usuarios
Content-Type: application/json

{
    "usermail": "a"
}

###
POST http://localhost:3000/api/grupos/1/coches
Content-Type: application/json

{
    "matricula": "123ABC"
}
###

DELETE http://localhost:3000/api/grupos/1/coches
Content-Type: application/json

{
    "matricula": "123ABC"
}


###
GET http://172.25.192.1:3000/api/grupo-usuarios?usermail=a