GET https://www.localizacar.info/api/user

###
GET https://www.localizacar.info/api/user/

###
POST https://www.localizacar.info/api/user
Content-Type: application/json

{
    "usermail": "john.doe@example.com",
    "userpassword": "securepassword123"
}


###
DELETE https://www.localizacar.info/api/user/john.doe@example.com
